### ISSUE TITLE
Week 03 - Day 3 - Function Juntion

### ISSUE THREAD

**Issue by gstark** [DylanAttal/assignments#10]
## Objectives

After completing this assignment, you should be able to:

- Demonstrate understanding of types, functions, argument-handling, loops, and conditional statements

## Requirements

1.  Fork [this repository](https://github.com/suncoast-devs/function-junction) to your own account.
2.  Change into your training directory
3.  Clone your repository: `hub clone function-junction`
4.  Change into your project's directory: `cd function-junction`
5.  Install the dependencies: `yarn install` (or just `yarn` for short)
6.  Open in Code: `code .`
7.  Start the test runner: `yarn test`
8.  Open `src/functions.test.js` and work on functions until tests pass.
9.  Commit and push your work to GitHub.
10. Turn in the URL to your GitHub repo.

### Explorer Mode

- [x] All tests passing
- [x] No linter warnings
- [x] Turn in the homework using the URL to your repository on Github.
- [x] *CAUTION* One the test is broken. Your job is to update the test to pass.

### Adventure Mode

- [x] If you used "built-in" JavaScript methods like `String.reverse()` or `Array.max()` to solve these problems, try implementing them from scratch.
- [x] Vice-versa: if you implemented your solutions from scratch, look in the documentation linked below to see if JavaScript has any built-in functions to help solve these problems.

### Epic Mode

- [ ] Expand the `sum` and `max` functions to take arrays instead of numbers and update the tests so they pass.
- [ ] Create your own simple functions with tests.
- [ ] Anytime in your code that you used a `for` loop or a `while` loop, convert it to use a `map`, `filter` or `reduce`.

## Additional Resources

Reference the documentation on MDN to find what kind of helpful functions might already be on `Array` and `String` in JavaScript.

- [String Functions on MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String).
- [Array Functions on MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array).

**Comment by DylanAttal** [comment]
https://github.com/DylanAttal/function-junction

**Comment by gstark** [comment]
Your homework was marked: **Exceeds Expectations**

![Woah](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBCdz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--5d5eae07a7d338c96b9a2cc704bc5ec7f53d072c/woah.gif)
> &ldquo;Woah&rdquo;
__&mdash; via **[Jason L Perry](https://gifs.suncoast.io/venerations/2)**__
