### ISSUE TITLE
Week 05 - Day 2 - JavaScript Iteration

### ISSUE THREAD

**Issue by gstark** [DylanAttal/assignments#16]
# JavaScript Iteration

## Objectives

After completing this assignment, you should be able to:

* Demonstrate an understanding of iteration/enumeration

## Instructions

1. Fork [this repository](https://github.com/suncoast-devs/js-iteration) to your own account.
2. Change into your projects directory:
3. Clone your repository: `git clone js-iteration`
4. Change into your project's directory: `cd js-iteration`
5. Install the dependencies: `yarn install` (or just `yarn` for short)
6. Open in your editor]
7. Start the test runner: `yarn test`
7. Open `src/functions.test.js` and work on functions until tests pass.
8. Commit and push your work to GitHub.
9. Turn in the URL to your GitHub repo.

## Explorer Mode

- All tests passing
- No linter warnings
- Turn in the homework using the URL to your repository on GitHub.

## Additional Resources

Reference the documentation on DevDocs to find what kind of helpful functions might already be in JavaScript.

- [String Functions on DevDocs](https://devdocs.io/javascript/global_objects/string).
- [Array Functions on DevDocs](http://devdocs.io/javascript/global_objects/array).

**Comment by DylanAttal** [comment]
https://github.com/DylanAttal/js-iteration

**Comment by gstark** [comment]
Excellent work!

**Comment by gstark** [comment]
Your homework was marked: **Exceeds Expectations**

![You got it!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBHUT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--d2c38988a8a66323675b11efd93094c28cccadde/cat%20rainbow.gif)
> &ldquo;You got it!&rdquo;
__&mdash; via **[Katherine Trammell](https://gifs.suncoast.io/venerations/15)**__
