### ISSUE TITLE
Week 05 - Day 3 - Thanksgiving Break Assignment

### ISSUE THREAD

**Issue by gstark** [DylanAttal/assignments#17]
# Choose one or more of the following:
- Try the [Javascript Koans](https://github.com/suncoast-devs/koans)
- Implement Blackjack in React
- Implement Tic-Tac-Toe in React
- Implement [this homework](https://suncoast.io/handbook/curriculum/front-end/react-ii/assignments/snowman/)
- Go through the free [Javascript 30](https://javascript30.com)

# Videos to Watch
- Watch this [amazing video](https://vimeo.com/36579366)

**Comment by DylanAttal** [comment]
https://github.com/DylanAttal/koans
https://github.com/DylanAttal/react-snowman

**Comment by gstark** [comment]
Your homework was marked: **Exceeds Expectations**

![You are amazing](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBJUT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--00e75725277d89ae8fc756a00a086407d1e278db/amazing.gif)
> &ldquo;You are amazing&rdquo;
__&mdash; via **[Katherine Trammell](https://gifs.suncoast.io/venerations/23)**__
