### ISSUE TITLE
Week 06 - Day 2 - One List

### ISSUE THREAD

**Issue by gstark** [DylanAttal/assignments#19]
In this assignment, you'll build a classic todo manager.

Something like: [One List](https://one-list.ambetha.surge.sh)

## Objectives

- Reinforce component architecture in React
- Effective use props and state in React

## Requirements

We're going to build todo manager. The user should be able to:
- Add new todo items
- Mark todo items as complete
- Delete todo items

Read the [documentation](https://one-list-api.herokuapp.com)

### Explorer Mode

- [x] Allow a todo to be created
- [x] Mark a todo complete
- [x] Delete a todo item

### Adventure Mode

- [ ] Allow the text of a todo item to be changed

### Epic Mode

- [ ] Allow for multiple lists by allowing the user to specify the `access token`

**Comment by DylanAttal** [comment]
https://github.com/DylanAttal/react-to-do-list

**Comment by gstark** [comment]
Your homework was marked: **Exceeds Expectations**

![Woooooh!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBTUT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--51a35f0aa3861c6c972e89ad3572a7cc7ad26dba/exceeds-1.gif)
> &ldquo;Woooooh!&rdquo;
__&mdash; via **[Mark Dewey](https://gifs.suncoast.io/venerations/63)**__
